name: cicd
on:
  push:
    branches: [ main ]
jobs:
  say-start: 
    runs-on: ubuntu-latest
    steps:
      - run: echo start

  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 149.28.228.217
        username: root
        password: c_J2sy@,gfoD!J%(
        port: 22
        command_timeout: 200m
        script: |
            whoami
            ls -al
            cd chaintify
            docker stop $(docker ps -aq)
            docker rm $(docker ps -aq)
            docker rmi $(docker images -q)
            docker system prune -a
            docker compose -f docker-compose.prod.yaml up -d
