name: cicd
on:
  push:
    branches: [ main ]
jobs:
  say-start: 
    runs-on: ubuntu-latest
    steps:
      - run: echo start

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 149.28.228.217
        username: root
        password: c_J2sy@,gfoD!J%(
        port: 22
        script: |
          whoami
          ls -al
